---
# roles/build-auto-provision-server/tasks/main.yml

- name: ensure root ownership on /var/www
  file:
    path: /var/www
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - auto-provision

- name: create docroot {{eqpress_docroot}}
  file:
    path: "{{eqpress_docroot}}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
    recurse: yes
  tags:
    - auto-provision

- name: create provision and provision-testing directories
  file:
    path: "{{eqpress_docroot}}/{{ item }}"
    state: directory
    owner: www-data
    group: www-data
    mode: '0755'
  loop:
    - provision
    - provision/pending
    - provision/processing
    - provision/processed
    - provision-testing
    - provision-testing/pending
    - provision-testing/processing
    - provision-testing/processed
  tags:
    - auto-provision
    - auto-provision-directories

- name: create monitor group
  group:
    name: "{{ item }}"
    state: present
  loop:
    - monitor
    - wordpress
  tags:
    - users

- name: create users
  user:
    name: "{{ item.user }}"
    group: "{{ item.group }}"
    shell: /bin/bash
  loop:
    - { user: "monitor", group: "monitor" }
    - { user: "wordpress", group: "wordpress" }
  tags:
    - users

- name: reset users home directory ownerships
  file:
    path: "/home/{{ item.user }}"
    owner: "{{ item.user }}"
    group: "{{ item.group }}"
    state: directory
    recurse: yes
  loop:
    - { user: "monitor", group: "monitor" }
  tags:
    - users

- name: set mode on sbin directory with no setuid bit
  file:
    path: /usr/local/sbin
    state: directory
    owner: root
    group: staff
    mode: 'u=rwx,g-s,g=rx,o=rx'
  tags:
    - sbin

- name: copy all sbin eqpress admin scripts
  copy:
    src: "{{ files }}/usr/local/sbin/{{ item }}"
    dest: /usr/local/sbin
    owner: root
    group: staff
    mode: '0755'
  loop:
    - check-mem.pl
    - class-http-log-parser.php
    - harden_ip.sh
    - resident-ram
    - top_ram_procs.sh
    - monit_check_mailq.sh
  tags:
    - sbin

- name: copy all sbin eqpress admin scripts templates
  template:
    src: "{{ files }}/usr/local/sbin/{{ item }}.j2"
    dest: /usr/local/sbin
    owner: root
    group: staff
    mode: '0755'
  loop:
    - monit_connections.sh

- name: copy custom monit startup script
  copy:
    src: "{{ files }}/etc/init.d/monit"
    dest: /etc/init.d
    owner: root
    group: root
    mode: '0750'
  notify:
    - restart monit
  tags:
    - monit

- name: copy custom monit-10 config
  template:
    src: "{{ files }}/etc/monit/monitrc-10_auto-provision.j2"
    dest: /etc/monit/monitrc-10
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart monit
  tags:
    - monit
    - monit-config
    - monitoring-email

- name: copy custom monit-60 config
  template:
    src: "{{ files }}/etc/monit/monitrc-60_auto-provision.j2"
    dest: /etc/monit/monitrc-60
    owner: root
    group: root
    mode: '0600'
  notify:
    - restart monit
  tags:
    - monit
    - monit-config
    - monitoring-email

- name: install auto-provision GPG key
  shell: gpg --keyserver hkp://keys.gnupg.net --recv-keys {{ auto_provision_gpg_id }}
  when: auto_provision_host is defined
  ignore_errors: yes
  tags:
    - auto-provision
    - gpg

- include_tasks: install-password-pusher.yml
