---
- hosts: all
  gather_facts: true
  vars:
    - updateing: yes
  roles:
     - common
     - gen-root-cert
     - ssh-config
     - eqpress-ssl
     - web-app
     - eqpress-console
     - eqpress-devops
     - mysql-percona-replication
     - eqpress-cronjob-deploy
     - nagios
