---

- name: install prerequisite for mcrypt
  apt:
    name:
      - php-pear
      - libmcrypt-dev
    state: present
  tags:
    - nginx
    - php

- name: get php extention directory
  shell: "/usr/bin/php --info 2>/dev/null | grep 'PHP Extension => ' | cut -d' ' -f4"
  register: php_extension
  changed_when: False
  tags:
    - nginx
    - php

- debug:
    msg: "Detected extension_dir = /usr/lib/php/{{php_extension.stdout}}"

- name: install mcrypt with pecl
  shell: |
    set timeout 300
    spawn pecl install mcrypt-1.0.2
    expect "autodetect\] : "
    send "\r"
    expect "You should add \"extension=mcrypt.so\" to php.ini\r"

    exit 0
  args:
    executable: /usr/bin/expect
    creates: "/usr/lib/php/{{php_extension.stdout}}/mcrypt.so"
  notify: reload php-fpm
  tags:
    - nginx
    - php

# This did not work because the pecl waits for input
#- name: install mcrypt with pecl
#  pear:
#    name: pecl/mcrypt-1.0.2
#    state: latest
#  notify: reload php-fpm
#  tags:
#    - nginx
#    - php

- name: install 20-mcrypt.ini in mods-available
  template:
    src: "{{files}}/etc/php/{{php_version}}/mods-available/mcrypt.ini.j2"
    dest: "/etc/php/{{php_version}}/mods-available/mcrypt.ini"
    mode: '0644'
    owner: root
    group: root
  notify: reload php-fpm
  tags:
    - nginx
    - php

- name: link mcrypt.ini enable
  file:
    src: "/etc/php/{{php_version}}/mods-available/mcrypt.ini"
    path: "/etc/php/{{php_version}}/fpm/conf.d/20-mcrypt.ini"
    state: link
  notify: reload php-fpm
  tags:
    - nginx
    - php

