---
- name: Generating RSA key for users 
  become: yes
  ansible.builtin.user:
    name: "{{ item }}"
    generate_ssh_key: yes
  loop:
    - root 
    - "{{ ansible_user_id }}"

- name: Downloading generated SSH public keys
  become: yes
  ansible.builtin.fetch:
    src: "{{ item }}/.ssh/id_rsa.pub"
    dest: "/tmp/id_rsa_{{ inventory_hostname }}.pub"
    flat: yes
  loop:
    - "/root"
    - "{{ ansible_user_dir }}"

- name: Copying slave's ssh key to master
  become: yes
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa_' + mysql_repl_slave + '.pub') }}"
  when:
    - mysql_repl_role is defined
    - mysql_repl_role == 'master'
    - mysql_repl_slave is defined
  loop:
    - root
    - "{{ ansible_user_id }}"

- name: Copying master's ssh key to slave
  become: yes
  ansible.builtin.authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa_' + mysql_repl_master + '.pub') }}"
  when:
    - mysql_repl_role is defined
    - mysql_repl_role == 'slave'
    - mysql_repl_master is defined
  loop:
    - root
    - "{{ ansible_user_id }}"

- name: known_hosts file on slave
  become: yes
  ansible.builtin.known_hosts:
    path: "{{ item }}/{{ ssh_known_hosts_file }}"
    name: "{{ mysql_repl_master }}"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan ' + mysql_repl_master + '') }}"
    hash_host: false
  when:
    - mysql_repl_role is defined
    - mysql_repl_role == 'slave'
    - mysql_repl_master is defined
  loop:
    - "/root"
    - "{{ ansible_user_dir }}"
  tags:
    - known_hosts

- name: known_hosts file on master
  become: yes
  ansible.builtin.known_hosts:
    path: "{{ item }}/{{ ssh_known_hosts_file }}"
    name: "{{ mysql_repl_slave }}"
    state: present
    key: "{{ lookup('pipe', 'ssh-keyscan ' + mysql_repl_slave + '') }}"
    hash_host: false
  when:
    - mysql_repl_role is defined
    - mysql_repl_role == 'master'
    - mysql_repl_slave is defined
  loop:
    - "/root"
    - "{{ ansible_user_dir }}"
  tags:
    - known_hosts

- name: Fix .ssh/ owner
  become: yes
  ansible.builtin.file:
    path: "{{ item.home }}/.ssh"
    owner: "{{ item.owner }}"
    recurse: yes
  loop:
    - { home: '/root', owner: 'root' }
    - { home: "{{ ansible_user_dir }}", owner: "{{ ansible_user_id }}" }
  tags:
    - known_hosts
