---
org_twitter: ''
auto_provision_ldap_server: ''
auto_provision_ldap_authattr: ''
auto_provision_ldap_basedn: ''
auto_provision_ldap_port: ''
provision_gpg_keyserver: "hkps://keyserver.ubuntu.com"

nodejs_repo: "https://deb.nodesource.com/node_22.x"
nodejs_gpg_key_url: "https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key"

rampass_repo: 'https://github.com/RamJett/rampass.git'
rampass_version: 'development'
