---
- name: systemd_daemon_reload
  become: yes
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart cron
  become: yes
  ansible.builtin.systemd:
    name: cron
    state: restarted

- name: enable_timer_edgespermit
  become: yes
  ansible.builtin.systemd:
    name: edgespermit.timer
    enabled: yes
    state: restarted

- name: enable_timer_mon_provision
  become: yes
  ansible.builtin.systemd:
    name: mon_provision.timer
    enabled: yes
    state: restarted

- name: enable_timer_mon_connections
  become: yes
  ansible.builtin.systemd:
    name: mon_connections.timer
    enabled: yes
    state: restarted

- name: enable_timer_mon_check-mailq
  become: yes
  ansible.builtin.systemd:
    name: mon_check-mailq.timer
    enabled: yes
    state: restarted

- name: noop
  ansible.builtin.debug:
    msg: "noop"
