#!/bin/bash
#
# Change the ownership and permssions for a WordPress docroot.
# Used by the lockdown option in eqpress console. If the user
# does not exist then user the wordpress user.
#
export PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/sbin:/usr/local/sbin

DOMAIN=$1
DOCROOT=/var/www/${DOMAIN}/wordpress

if [ -d ${DOCROOT} ]; then
	USER_INFO=($(grep DB_USER ${DOCROOT}/wp-config.php |tr "'" '\n'))
	USER=${USER_INFO[3]}

	if ! grep ${USER} /etc/passwd > /dev/null; then
		USER=wordpress
	fi

	ionice -c 3 chown -R ${USER}:wordpress ${DOCROOT}

	# Change file mode of directories to 755
	ionice -c 3 find "${DOCROOT}" -type d -print0 | xargs -0 -r chmod 755

	# Change file mode of files to 644
	ionice -c 3 find "${DOCROOT}" -type f -print0 | xargs -0 -r chmod 644
	echo ${DOMAIN} has been locked down.
else
	echo ${DOCROOT} does not exist. Lockdown failed.
fi
