---
- debug:
    msg: "{{ ansible_version }}"

- name: check if Ubuntu and is version greater than {{ min_distribution_version }}
  ansible.builtin.fail:
    msg: "FAILED - '{{ ansible_distribution }}' version '{{ ansible_distribution_major_version }}'"
  when:
    - ansible_distribution_version is version(min_distribution_version,'<') or ansible_distribution != 'Ubuntu'

- name: check that play set variables are set
  ansible.builtin.fail:
    msg: "FAILED - '{{ item }}' variable not set"
  when: "item is not defined" 
  loop:
    - is_local
    - host_count

- name: make sure we are only running for right number of hosts 
  local_action:
    module: fail
    msg: "The number of nodes must be exactly {{ host_count }}!"
  when: "play_hosts|length != host_count"
  run_once: yes
