#!/bin/bash
#
# Change the ownership and permissions for a WordPress docroot.
# Used by the lockdown option in easyPress console. If the user
# does not exist then use the wordpress user.
#
export PATH=/bin:/usr/bin:/usr/local/bin:/usr/sbin:/sbin:/usr/local/sbin

DOMAIN=$1
DOCROOT=/var/www/${DOMAIN}/wordpress

if [ -d ${DOCROOT} ]; then
	USER_INFO=($(grep DB_USER ${DOCROOT}/wp-config.php |tr "'" '\n'))
	USER=${USER_INFO[3]}

	if ! grep ${USER} /etc/passwd > /dev/null; then
		USER=wordpress
	fi

	ionice -c 3 chown -R ${USER}:wordpress ${DOCROOT}
	ionice -c 3 find ${DOCROOT} -type d -exec chmod 755 {} \;
	ionice -c 3 find ${DOCROOT} -type f -exec chmod 644 {} \;
	echo ${DOMAIN} has been locked down.
else
	echo ${DOCROOT} does not exist. Lockdown failed.
fi
