#!/bin/sh
### BEGIN INIT INFO
# Provides:          monit
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Should-Start:      $all
# Should-Stop:       $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: service and resource monitoring daemon
# Description:       monit is a utility for managing and monitoring
#                    processes, programs, files, directories and filesystems
#                    on a Unix system. Monit conducts automatic maintenance
#                    and repair and can execute meaningful causal actions
#                    in error situations.
### END INIT INFO


PATH=/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=`which monit`
CONF="monitrc-60 monitrc-10"
PIDS="monit-60 monit-10"
DESC="monit: general purpose monitor"

# Check if DAEMON binary exist
test -f $DAEMON || exit 0

case "$1" in
  start)
	for MC in $CONF; do
		echo -n "Starting $DESC: "
		echo -n "$MC"
		start-stop-daemon -v -S --quiet -n $MC --exec $DAEMON > /dev/null 2>&1 -- -c /etc/monit/$MC
		echo "."
	done
	;;
  stop)
	for NAME in $PIDS; do
		echo -n "Stopping $DESC: "
		echo -n "$NAME"
		start-stop-daemon --retry 5 --oknodo --stop --quiet --pidfile /var/run/$NAME.pid \
			--exec $DAEMON  > /dev/null 2>&1
		echo "."
	done
	;;
  restart|force-reload)
	$0 stop
	$0 start
	;;
  *)
	N=/etc/init.d/monit
	echo "Usage: $N {start|stop|restart}" >&2
	exit 1
	;;
esac

exit 0
