#!/bin/sh

### BEGIN INIT INFO
# Provides:	  nginx-create-cachedir
# Required-Start:    $local_fs 
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: creates the nginx web server cache directory on tmpfs and on-disk
# Description:       creates the nginx web server cache directory on tmpfs and on-disk
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
NAME=nginx-create-cachedir
DESC="Create the nginx web server cache directory on tmpfs and on-disk"
CACHE=/run/cache/nginx
ONDISK=/var/cache/nginx-ondisk
OWNER=www-data

set -e

. /lib/lsb/init-functions


start() {
	if [ -d $CACHE ]; then
        	echo "nginx tmpfs cache already exits"
        	/bin/chown -R $OWNER $CACHE

	else
        	/bin/mkdir -p $CACHE
        	/bin/chown -R $OWNER $CACHE
	fi

	if [ -d $ONDISK ]; then
		echo "nginx on-disk cache already exits"
		/bin/chown -R $OWNER $ONDISK
	else
		/bin/mkdir -p $ONDISK
		/bin/chown -R $OWNER $ONDISK
	fi
}

stop() {
	/bin/true
}

case "$1" in
	start)
		log_daemon_msg "Starting $DESC" "$NAME"
		start
		log_end_msg $?
		;;

	stop)
		log_daemon_msg "Stopping $DESC" "$NAME"
		stop
		log_end_msg $?
		;;

	*)
		echo "Usage: $NAME {start|stop}" >&2
		exit 1
		;;
esac

exit 0
