---
# common/handlers/main.yml

- name: update tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  ignore_errors: yes

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: restart ssh
  systemd:
    name: ssh
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: restart firewall
  command: /etc/network/if-down.d/iptables_save && /etc/network/if-pre-up.d/iptables

- name: start firewall
  command: /etc/network/if-pre-up.d/iptables

- name: harden IP stack
  command: /usr/local/sbin/harden_ip.sh
  ignore_errors: yes

- name: restart postfix
  systemd:
    name: postfix
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    enabled: yes
  ignore_errors: yes

- name: restart mysql
  systemd:
    name: mysql
    state: restarted
    eneabled: yes
  ignore_errors: yes

- name: sysctl reload
  command: sysctl --system

- name: reboot the server
  action: command /sbin/reboot
