---
- name: create directories
  ansible.builtin.file:
    path: "{{ item.dir }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "0700"
    state: directory
  loop:
    - { dir: '{{ ansible_user_dir }}/docker', owner: '{{ ansible_user_id }}', group: '{{ ansible_user_gid }}' }
    - { dir: '{{ ansible_user_dir }}/docker/eqpress_nginx', owner: '{{ ansible_user_id }}', group: '{{ ansible_user_gid }}' }
  tags:
    - nginx_docker

- name: add "{{ docker_group }}" to user "{{ ansible_user_id }}"
  become: yes
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    create_home: no
    append: yes
    groups: "{{ docker_group }}"
  tags:
    - nginx_docker

- name: create docker-compose.yaml got nginx
  ansible.builtin.template:
    dest: "{{ ansible_user_dir }}/docker/eqpress_nginx/docker-compose.yaml"
    src: nginx-compose.yaml.j2
    mode: '0640'
  tags:
    - nginx_docker

- name: install dockerized nginx command
  become: yes
  ansible.builtin.template:
    dest: /usr/local/sbin/docker-nginx
    src: docker-nginx.j2
    owner: root
    group: root
    mode: "0755"
  tags:
    - nginx_docker_script
    - nginx_docker

- name: symlink docker-nginx -> /usr/sbin/nginx
  become: yes
  ansible.builtin.file:
    src: /usr/local/sbin/docker-nginx
    dest: /usr/sbin/nginx
    owner: root
    group: root
    state: link
  tags:
    - nginx_docker_script
    - nginx_docker

