---
# roles/init-auto-provision/tasks/main.yml

- name: Use DNS for host external IPv4 address master
  local_action:
    module: command /usr/bin/dig +noall +short {{ auto_provision_server }}
  when: use_host_lookup is defined and use_host_lookup
  register: dns_ip_ap

- name: generate random strings
  local_action:
    module: shell < /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c {{ item.size }}
  register: rand_result
  loop:
    - { size: '{{15|random(10,1)}}' }
    - { size: '{{15|random(10,1)}}' }
    - { size: '32' }
    - { size: '{{15|random(10,1)}}' }

- name: Create the main variables file.
  local_action:
    module: template
    src: auto-provision.yml.j2
    dest: "{{ playbook_dir }}/group_vars/auto-provision.yml"
