---
- hosts: all
  any_errors_fatal: yes
  gather_facts: yes

  vars:
    - is_local: no
    - host_count: 2

  roles:
    - prerequisites 
    - common
    - firewall-hardening
    - ssh-config
    - eqpress-ssl
    - eqpress-sysops
    - eqpress-root
    - php-services
    - nginx-web-services
    - mariadb-local-service
    - mariadb-local-enable-replication
    - postfix-email-service
    - timed-jobs
