---
- name: Check for --limit and generate group list
  hosts: localhost
  gather_facts: false
  vars:
    available_groups: []

  tasks:
    - name: Generate list of available groups
      set_fact:
        available_groups: "{{ available_groups + [item] }}"
      loop: "{{ groups.keys() }}"
      when:
        - groups[item] | length > 0
        - item != 'all'
        - item != 'ungrouped'
        - item != 'provision'
      tags: always

    - name: Guessed Available Cluster Names
      debug:
        msg: "Guessed Available Clusters: {{ available_groups | join(', ') }}"
      tags: always

    - name: fail
      fail:
        msg: "This playbook is meant to be ran with '-l cluster_name' . See list above"
      tags: always

- hosts: all
  any_errors_fatal: yes
  gather_facts: yes

  vars:
    is_local: no

  roles:
    - prerequisites 
    - common
    - firewall-hardening
    - ssh-config
    - ssl-config
    - sysops
    - root
    - docker
    - php-services
    - nginx-web-services
    - mariadb-local-service
    - mariadb-local-enable-replication
    - postfix-email-service
    - telegraf-client
    - timed-jobs

  tasks:
    - name: create TOOLS_FAQ
      become: yes
      ansible.builtin.shell: |
         echo $SEP > $FAQ ; echo "These are commonly used tools" >> $FAQ ; echo $SEP >> $FAQ
         echo "Commands:" >> $FAQ
         echo "* edgespermit" >> $FAQ
         echo "* php-update-pool.php" >> $FAQ
         echo "* wp" >> $FAQ
         echo $SEP >> $FAQ
         echo "* edgespermit" >> $FAQ ; echo >> $FAQ
         /usr/local/sbin/edgespermit -h >> $FAQ ; echo $SEP >> $FAQ
         echo "* php-update-pool.php" >> $FAQ ; echo >> $FAQ
         /usr/local/sbin/php-update-pool.php -h >> $FAQ ; echo $SEP >> $FAQ
         echo " * wp" >> $FAQ ; echo >> $FAQ
         WP_HELP="$(/usr/local/sbin/wp --allow-root help)"
         echo "$WP_HELP" >> $FAQ ; echo $SEP >> $FAQ
      environment:
        - FAQ: "{{ ansible_user_dir }}/TOOLS_FAQ"
        - SEP: "=============================================================================================="
      tags:
        - faq
