---
- hosts: provision
  gather_facts: yes

  vars:
    - is_local: no

  roles:
     - prerequisites
     - common
     - ssh-config
     - ssl-config
     - firewall-hardening
     - postfix-email-service
     - php-services
     - mariadb-local-service
     - sysops
     - nginx-web-services
     - provision-server
